# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='homepage/features')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('ordering',),
            },
        ),
    ]
