# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(editable=False, verbose_name='object ID')),
                ('subtitle', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_field', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('stickiness', models.PositiveIntegerField()),
                ('cta_text', models.CharField(blank=True, default='Find out more', max_length=30, null=True, verbose_name='call-to-action text')),
                ('cta_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='call-to-action URL')),
                ('added', models.DateTimeField()),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-added',),
                'get_latest_by': 'added',
            },
        ),
    ]
