# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 09:03
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookahead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
        migrations.CreateModel(
            name='LookaheadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('lookahead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='traffic.Lookahead')),
            ],
        ),
        migrations.CreateModel(
            name='MixcloudSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('criteria',),
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('mon_start', models.CharField(blank=True, max_length=5, null=True)),
                ('mon_end', models.CharField(blank=True, max_length=5, null=True)),
                ('tue_start', models.CharField(blank=True, max_length=5, null=True)),
                ('tue_end', models.CharField(blank=True, max_length=5, null=True)),
                ('wed_start', models.CharField(blank=True, max_length=5, null=True)),
                ('wed_end', models.CharField(blank=True, max_length=5, null=True)),
                ('thu_start', models.CharField(blank=True, max_length=5, null=True)),
                ('thu_end', models.CharField(blank=True, max_length=5, null=True)),
                ('fri_start', models.CharField(blank=True, max_length=5, null=True)),
                ('fri_end', models.CharField(blank=True, max_length=5, null=True)),
                ('sat_start', models.CharField(blank=True, max_length=5, null=True)),
                ('sat_end', models.CharField(blank=True, max_length=5, null=True)),
                ('sun_start', models.CharField(blank=True, max_length=5, null=True)),
                ('sun_end', models.CharField(blank=True, max_length=5, null=True)),
                ('recurrence', models.IntegerField(choices=[(7, 'every week'), (14, 'every 2 weeks'), (-2, 'every month'), (-1, 'one-off')], default=7)),
                ('monthly_number', models.PositiveIntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (6, 'last')], null=True)),
                ('monthly_weekday', models.PositiveIntegerField(blank=True, choices=[(2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (0, 'Monday'), (1, 'Tuesday'), (6, 'Sunday'), (5, 'Saturday')], null=True)),
                ('next_air_date', models.DateField(blank=True, help_text='Used to determine what to use as a base date for shows that are not weekly', null=True)),
                ('archived', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, max_length=255, null=True, upload_to='upload_programme_banner')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='upload_programme_logo')),
            ],
            options={
                'ordering': ('name', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='ProgrammeHiatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiatuses', to='traffic.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammePresenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='talent.Presenter')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.Programme')),
            ],
            options={
                'db_table': 'traffic_programme_presenters',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('kind', models.CharField(choices=[('info', 'Information'), ('warn', 'Warning'), ('danger', 'Danger'), ('success', 'Success'), ('episode', 'Episode'), ('post', 'Blog post')], max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_updates', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='traffic.Programme')),
            ],
            options={
                'ordering': ('-date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.AddField(
            model_name='programme',
            name='presenters',
            field=models.ManyToManyField(through='traffic.ProgrammePresenter', to='talent.Presenter'),
        ),
        migrations.AddField(
            model_name='programme',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='traffic.Series'),
        ),
        migrations.AddField(
            model_name='mixcloudsearch',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixcloud_searches', to='traffic.Programme'),
        ),
        migrations.AddField(
            model_name='lookaheaditem',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookaheads', to='traffic.Programme'),
        ),
        migrations.AlterUniqueTogether(
            name='programmepresenter',
            unique_together=set([('presenter', 'programme')]),
        ),
        migrations.AlterUniqueTogether(
            name='programmehiatus',
            unique_together=set([('date', 'programme')]),
        ),
        migrations.AlterUniqueTogether(
            name='mixcloudsearch',
            unique_together=set([('criteria', 'programme')]),
        ),
        migrations.AlterUniqueTogether(
            name='lookaheaditem',
            unique_together=set([('programme', 'lookahead')]),
        ),
    ]
