# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_filepicker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', django_filepicker.models.FPFileField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Playlist')),
            ],
            options={
                'db_table': 'music_playlist_tracks',
                'ordering': ('track__artist__name', 'track__title'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artwork', django_filepicker.models.FPFileField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(blank=True, null=True)),
                ('sample_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='sample URL')),
                ('purchase_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='purchase URL')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.Artist')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='music.Track'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='music.PlaylistTrack', to='music.Track'),
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together=set([('track', 'playlist')]),
        ),
    ]
