# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('short_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='upload_presenter_photo')),
                ('biography', models.TextField(blank=True, null=True)),
                ('alumnus', models.BooleanField(default=False)),
                ('twitter_username', models.CharField(blank=True, max_length=30, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presenter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
